### ISSUE TITLE
Update JSON output

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstr#19] opened 2021-05-28 23:03 UTC
I recently changed [the scenario format](https://a-b-street.github.io/docs//dev/formats/scenarios.html) to remove `origin` on the person object, and include `origin` on every single trip.

I think it's a simple code change:
1) Remove `origin` at https://github.com/a-b-street/abstr/blob/a417c93b12d5b2513333c39ab33b1762706abc16/R/ab_scenario.R#L192
2) Add `origin` at https://github.com/a-b-street/abstr/blob/a417c93b12d5b2513333c39ab33b1762706abc16/R/ab_scenario.R#L182

**Comment by Robinlovelace** [comment] 2021-05-29 05:19
Thanks for this Dustin, will take a look soon. The package also needs updating for #18.

**Comment by Robinlovelace** [comment] 2021-06-11 22:03
Closed in #19. Could do with better documentation but I think the issue is sorted, for now.

**Closed by Robinlovelace** 2021-06-11 22:03 UTC
